import firebase_admin
from firebase_admin import credentials, firestore
cred = credentials.Certificate('service-account.json')
firebase_admin.initialize_app(cred)
db = firestore.client()
docs = [
    {'passageId': 'ESO-FP-W1-001', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'EDU', 'question': 'Should students with disabilities always be fully included in mainstream classrooms?', 'promptDescription': 'Should students with disabilities always be fully included in mainstream classrooms?', 'status': 'active', 'curr': False, 'sourceId': 'EDU-002', 'framesWeek': 'W1', 'framesFrame': 'Scale & Stakeholder', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_01'},
    {'passageId': 'ESO-FP-W1-002', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'WRK', 'question': 'Should companies be required to provide childcare for employees?', 'promptDescription': 'Should companies be required to provide childcare for employees?', 'status': 'active', 'curr': False, 'sourceId': 'WRK-001', 'framesWeek': 'W1', 'framesFrame': 'Scale & Stakeholder', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_01'},
    {'passageId': 'ESO-FP-W1-003', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'ECN', 'question': 'Should countries adopt a global minimum corporate tax?', 'promptDescription': 'Should countries adopt a global minimum corporate tax?', 'status': 'active', 'curr': False, 'sourceId': 'ECN-007', 'framesWeek': 'W1', 'framesFrame': 'Scale & Stakeholder', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_01'},
    {'passageId': 'ESO-FP-W1-004', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'GOV', 'question': 'Should governments be required to consult citizens directly on major policy decisions?', 'promptDescription': 'Should governments be required to consult citizens directly on major policy decisions?', 'status': 'active', 'curr': False, 'sourceId': 'GOV-013', 'framesWeek': 'W1', 'framesFrame': 'Scale & Stakeholder', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_01'},
    {'passageId': 'ESO-FP-W1-005', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'HLT', 'question': 'Should mental health services be equally funded as physical health services?', 'promptDescription': 'Should mental health services be equally funded as physical health services?', 'status': 'active', 'curr': False, 'sourceId': 'HLT-002', 'framesWeek': 'W1', 'framesFrame': 'Scale & Stakeholder', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_01'},
    {'passageId': 'ESO-FP-W1-006', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'TEC', 'question': 'Should tech companies be required to pay taxes in every country they operate?', 'promptDescription': 'Should tech companies be required to pay taxes in every country they operate?', 'status': 'active', 'curr': False, 'sourceId': 'TEC-005', 'framesWeek': 'W1', 'framesFrame': 'Scale & Stakeholder', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_01'},
    {'passageId': 'ESO-FP-W1-007', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'INT', 'question': 'Should countries be required to contribute to a global climate fund?', 'promptDescription': 'Should countries be required to contribute to a global climate fund?', 'status': 'active', 'curr': False, 'sourceId': 'INT-009', 'framesWeek': 'W1', 'framesFrame': 'Scale & Stakeholder', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_01'},
    {'passageId': 'ESO-FP-W1-008', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'CUL', 'question': 'Should governments fund the preservation of indigenous cultural practices?', 'promptDescription': 'Should governments fund the preservation of indigenous cultural practices?', 'status': 'active', 'curr': False, 'sourceId': 'CUL-010', 'framesWeek': 'W1', 'framesFrame': 'Scale & Stakeholder', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_01'},
    {'passageId': 'ESO-FP-W2-001', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'EDU', 'question': 'Should higher education be made tuition-free at public universities?', 'promptDescription': 'Should higher education be made tuition-free at public universities?', 'status': 'active', 'curr': False, 'sourceId': 'EDU-007', 'framesWeek': 'W2', 'framesFrame': 'Trade-offs & Constraints', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_02'},
    {'passageId': 'ESO-FP-W2-002', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'WRK', 'question': 'Should gig economy workers receive the same benefits as full-time employees?', 'promptDescription': 'Should gig economy workers receive the same benefits as full-time employees?', 'status': 'active', 'curr': False, 'sourceId': 'WRK-002', 'framesWeek': 'W2', 'framesFrame': 'Trade-offs & Constraints', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_02'},
    {'passageId': 'ESO-FP-W2-003', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'ECN', 'question': 'Should governments implement universal basic income?', 'promptDescription': 'Should governments implement universal basic income?', 'status': 'active', 'curr': False, 'sourceId': 'ECN-002', 'framesWeek': 'W2', 'framesFrame': 'Trade-offs & Constraints', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_02'},
    {'passageId': 'ESO-FP-W2-004', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'GOV', 'question': 'Should social media companies be required to remove political misinformation?', 'promptDescription': 'Should social media companies be required to remove political misinformation?', 'status': 'active', 'curr': False, 'sourceId': 'GOV-009', 'framesWeek': 'W2', 'framesFrame': 'Trade-offs & Constraints', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_02'},
    {'passageId': 'ESO-FP-W2-005', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'HLT', 'question': 'Should alternative medicine be covered by public health insurance?', 'promptDescription': 'Should alternative medicine be covered by public health insurance?', 'status': 'active', 'curr': False, 'sourceId': 'HLT-010', 'framesWeek': 'W2', 'framesFrame': 'Trade-offs & Constraints', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_02'},
    {'passageId': 'ESO-FP-W2-006', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'TEC', 'question': 'Should governments regulate the development of artificial intelligence?', 'promptDescription': 'Should governments regulate the development of artificial intelligence?', 'status': 'active', 'curr': False, 'sourceId': 'TEC-001', 'framesWeek': 'W2', 'framesFrame': 'Trade-offs & Constraints', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_02'},
    {'passageId': 'ESO-FP-W2-007', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'ENV', 'question': 'Should governments ban the development of new fossil fuel infrastructure?', 'promptDescription': 'Should governments ban the development of new fossil fuel infrastructure?', 'status': 'active', 'curr': False, 'sourceId': 'ENV-011', 'framesWeek': 'W2', 'framesFrame': 'Trade-offs & Constraints', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_02'},
    {'passageId': 'ESO-FP-W2-008', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'JUS', 'question': 'Should governments implement stricter gun control measures?', 'promptDescription': 'Should governments implement stricter gun control measures?', 'status': 'active', 'curr': False, 'sourceId': 'JUS-009', 'framesWeek': 'W2', 'framesFrame': 'Trade-offs & Constraints', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_02'},
    {'passageId': 'ESO-FP-W3-001', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'EDU', 'question': 'Should schools integrate media literacy education into their curricula?', 'promptDescription': 'Should schools integrate media literacy education into their curricula?', 'status': 'active', 'curr': False, 'sourceId': 'EDU-020', 'framesWeek': 'W3', 'framesFrame': 'Causal Systems', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_03'},
    {'passageId': 'ESO-FP-W3-002', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'WRK', 'question': 'Should the gig economy be more strictly regulated?', 'promptDescription': 'Should the gig economy be more strictly regulated?', 'status': 'active', 'curr': False, 'sourceId': 'WRK-013', 'framesWeek': 'W3', 'framesFrame': 'Causal Systems', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_03'},
    {'passageId': 'ESO-FP-W3-003', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'ECN', 'question': 'Should there be stronger antitrust laws to break up monopolies?', 'promptDescription': 'Should there be stronger antitrust laws to break up monopolies?', 'status': 'active', 'curr': False, 'sourceId': 'ECN-003', 'framesWeek': 'W3', 'framesFrame': 'Causal Systems', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_03'},
    {'passageId': 'ESO-FP-W3-004', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'GOV', 'question': 'Should governments implement stricter regulations on lobbying?', 'promptDescription': 'Should governments implement stricter regulations on lobbying?', 'status': 'active', 'curr': False, 'sourceId': 'GOV-023', 'framesWeek': 'W3', 'framesFrame': 'Causal Systems', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_03'},
    {'passageId': 'ESO-FP-W3-005', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'HLT', 'question': 'Should governments implement sugar taxes on processed foods?', 'promptDescription': 'Should governments implement sugar taxes on processed foods?', 'status': 'active', 'curr': False, 'sourceId': 'HLT-001', 'framesWeek': 'W3', 'framesFrame': 'Causal Systems', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_03'},
    {'passageId': 'ESO-FP-W3-006', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'TEC', 'question': 'Should governments regulate the use of social media algorithms?', 'promptDescription': 'Should governments regulate the use of social media algorithms?', 'status': 'active', 'curr': False, 'sourceId': 'TEC-017', 'framesWeek': 'W3', 'framesFrame': 'Causal Systems', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_03'},
    {'passageId': 'ESO-FP-W3-007', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'ENV', 'question': 'Should governments implement a carbon tax on all fossil fuel usage?', 'promptDescription': 'Should governments implement a carbon tax on all fossil fuel usage?', 'status': 'active', 'curr': False, 'sourceId': 'ENV-001', 'framesWeek': 'W3', 'framesFrame': 'Causal Systems', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_03'},
    {'passageId': 'ESO-FP-W3-008', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'INT', 'question': 'Should there be stricter international regulations on deep-sea fishing?', 'promptDescription': 'Should there be stricter international regulations on deep-sea fishing?', 'status': 'active', 'curr': False, 'sourceId': 'INT-007', 'framesWeek': 'W3', 'framesFrame': 'Causal Systems', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_03'},
    {'passageId': 'ESO-FP-W4-001', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'EDU', 'question': 'Should AI teachers replace human instructors in some schools?', 'promptDescription': 'Should AI teachers replace human instructors in some schools?', 'status': 'active', 'curr': False, 'sourceId': 'EDU-016', 'framesWeek': 'W4', 'framesFrame': 'Hypothetical & Conditional', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_04'},
    {'passageId': 'ESO-FP-W4-002', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'EDU', 'question': 'Should personalized learning algorithms be mandatory in public education?', 'promptDescription': 'Should personalized learning algorithms be mandatory in public education?', 'status': 'active', 'curr': False, 'sourceId': 'EDU-017', 'framesWeek': 'W4', 'framesFrame': 'Hypothetical & Conditional', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_04'},
    {'passageId': 'ESO-FP-W4-003', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'ECN', 'question': 'Should cryptocurrency be regulated as a financial instrument?', 'promptDescription': 'Should cryptocurrency be regulated as a financial instrument?', 'status': 'active', 'curr': False, 'sourceId': 'ECN-006', 'framesWeek': 'W4', 'framesFrame': 'Hypothetical & Conditional', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_04'},
    {'passageId': 'ESO-FP-W4-004', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'ECN', 'question': 'Should central banks adopt digital currencies?', 'promptDescription': 'Should central banks adopt digital currencies?', 'status': 'active', 'curr': False, 'sourceId': 'ECN-013', 'framesWeek': 'W4', 'framesFrame': 'Hypothetical & Conditional', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_04'},
    {'passageId': 'ESO-FP-W4-005', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'GOV', 'question': 'Should governments implement a digital identity system for all citizens?', 'promptDescription': 'Should governments implement a digital identity system for all citizens?', 'status': 'active', 'curr': False, 'sourceId': 'GOV-010', 'framesWeek': 'W4', 'framesFrame': 'Hypothetical & Conditional', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_04'},
    {'passageId': 'ESO-FP-W4-006', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'HLT', 'question': 'Should governments fund research into life extension technologies?', 'promptDescription': 'Should governments fund research into life extension technologies?', 'status': 'active', 'curr': False, 'sourceId': 'HLT-017', 'framesWeek': 'W4', 'framesFrame': 'Hypothetical & Conditional', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_04'},
    {'passageId': 'ESO-FP-W4-007', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'TEC', 'question': 'Should there be a global moratorium on autonomous weapons development?', 'promptDescription': 'Should there be a global moratorium on autonomous weapons development?', 'status': 'active', 'curr': False, 'sourceId': 'TEC-007', 'framesWeek': 'W4', 'framesFrame': 'Hypothetical & Conditional', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_04'},
    {'passageId': 'ESO-FP-W4-008', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'INT', 'question': 'Should there be a global ban on nuclear weapons?', 'promptDescription': 'Should there be a global ban on nuclear weapons?', 'status': 'active', 'curr': False, 'sourceId': 'INT-005', 'framesWeek': 'W4', 'framesFrame': 'Hypothetical & Conditional', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_04'},
    {'passageId': 'ESO-FP-W5-001', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'EDU', 'question': 'Should universities limit legacy admissions?', 'promptDescription': 'Should universities limit legacy admissions?', 'status': 'active', 'curr': False, 'sourceId': 'EDU-008', 'framesWeek': 'W5', 'framesFrame': 'Values, Heuristics & Bias', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_05'},
    {'passageId': 'ESO-FP-W5-002', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'WRK', 'question': 'Should companies be required to disclose pay scales for all positions?', 'promptDescription': 'Should companies be required to disclose pay scales for all positions?', 'status': 'active', 'curr': False, 'sourceId': 'WRK-005', 'framesWeek': 'W5', 'framesFrame': 'Values, Heuristics & Bias', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_05'},
    {'passageId': 'ESO-FP-W5-003', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'ECN', 'question': 'Should inheritance taxes be significantly increased?', 'promptDescription': 'Should inheritance taxes be significantly increased?', 'status': 'active', 'curr': False, 'sourceId': 'ECN-004', 'framesWeek': 'W5', 'framesFrame': 'Values, Heuristics & Bias', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_05'},
    {'passageId': 'ESO-FP-W5-004', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'GOV', 'question': 'Should there be stricter limits on political donations from corporations?', 'promptDescription': 'Should there be stricter limits on political donations from corporations?', 'status': 'active', 'curr': False, 'sourceId': 'GOV-004', 'framesWeek': 'W5', 'framesFrame': 'Values, Heuristics & Bias', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_05'},
    {'passageId': 'ESO-FP-W5-005', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'HLT', 'question': 'Should euthanasia be legalized in all countries?', 'promptDescription': 'Should euthanasia be legalized in all countries?', 'status': 'active', 'curr': False, 'sourceId': 'HLT-003', 'framesWeek': 'W5', 'framesFrame': 'Values, Heuristics & Bias', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_05'},
    {'passageId': 'ESO-FP-W5-006', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'TEC', 'question': 'Should governments regulate the collection and use of biometric data?', 'promptDescription': 'Should governments regulate the collection and use of biometric data?', 'status': 'active', 'curr': False, 'sourceId': 'TEC-009', 'framesWeek': 'W5', 'framesFrame': 'Values, Heuristics & Bias', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_05'},
    {'passageId': 'ESO-FP-W5-007', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'JUS', 'question': 'Should private prisons be banned?', 'promptDescription': 'Should private prisons be banned?', 'status': 'active', 'curr': False, 'sourceId': 'JUS-002', 'framesWeek': 'W5', 'framesFrame': 'Values, Heuristics & Bias', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_05'},
    {'passageId': 'ESO-FP-W5-008', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'INT', 'question': 'Should there be stricter international regulations on the use of private military companies?', 'promptDescription': 'Should there be stricter international regulations on the use of private military companies?', 'status': 'active', 'curr': False, 'sourceId': 'INT-013', 'framesWeek': 'W5', 'framesFrame': 'Values, Heuristics & Bias', 'suggestedFocusArea': 'discourse_frame', 'suggestedPrimaryFrame': 'FRAME_05'},
    {'passageId': 'ESO-FP-W6-001', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'EDU', 'question': 'Should vocational education be prioritized over academic preparation?', 'promptDescription': 'Should vocational education be prioritized over academic preparation?', 'status': 'active', 'curr': False, 'sourceId': 'EDU-013', 'framesWeek': 'W6', 'framesFrame': 'Synthesis & Judgment', 'suggestedFocusArea': 'combined', 'suggestedPrimaryFrame': 'FRAME_06'},
    {'passageId': 'ESO-FP-W6-002', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'GOV', 'question': 'Should the electoral college be abolished?', 'promptDescription': 'Should the electoral college be abolished?', 'status': 'active', 'curr': False, 'sourceId': 'GOV-007', 'framesWeek': 'W6', 'framesFrame': 'Synthesis & Judgment', 'suggestedFocusArea': 'combined', 'suggestedPrimaryFrame': 'FRAME_06'},
    {'passageId': 'ESO-FP-W6-003', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'GOV', 'question': 'Should judges be elected or appointed?', 'promptDescription': 'Should judges be elected or appointed?', 'status': 'active', 'curr': False, 'sourceId': 'GOV-014', 'framesWeek': 'W6', 'framesFrame': 'Synthesis & Judgment', 'suggestedFocusArea': 'combined', 'suggestedPrimaryFrame': 'FRAME_06'},
    {'passageId': 'ESO-FP-W6-004', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'EDU', 'question': 'Should education systems prioritize critical thinking over content knowledge?', 'promptDescription': 'Should education systems prioritize critical thinking over content knowledge?', 'status': 'active', 'curr': False, 'sourceId': 'EDU-028', 'framesWeek': 'W6', 'framesFrame': 'Synthesis & Judgment', 'suggestedFocusArea': 'combined', 'suggestedPrimaryFrame': 'FRAME_06'},
    {'passageId': 'ESO-FP-W6-005', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'CUL', 'question': 'Should there be stricter regulations on the use of cultural appropriation in art?', 'promptDescription': 'Should there be stricter regulations on the use of cultural appropriation in art?', 'status': 'active', 'curr': False, 'sourceId': 'CUL-018', 'framesWeek': 'W6', 'framesFrame': 'Synthesis & Judgment', 'suggestedFocusArea': 'combined', 'suggestedPrimaryFrame': 'FRAME_06'},
    {'passageId': 'ESO-FP-W6-006', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'ECN', 'question': 'Should governments provide universal healthcare as an economic right?', 'promptDescription': 'Should governments provide universal healthcare as an economic right?', 'status': 'active', 'curr': False, 'sourceId': 'ECN-016', 'framesWeek': 'W6', 'framesFrame': 'Synthesis & Judgment', 'suggestedFocusArea': 'combined', 'suggestedPrimaryFrame': 'FRAME_06'},
    {'passageId': 'ESO-FP-W6-007', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'TEC', 'question': 'Should tech companies be required to make their algorithms transparent?', 'promptDescription': 'Should tech companies be required to make their algorithms transparent?', 'status': 'active', 'curr': False, 'sourceId': 'TEC-027', 'framesWeek': 'W6', 'framesFrame': 'Synthesis & Judgment', 'suggestedFocusArea': 'combined', 'suggestedPrimaryFrame': 'FRAME_06'},
    {'passageId': 'ESO-FP-W6-008', 'taskType': 'ESO', 'corpusType': 'ESO', 'domain': 'ENV', 'question': 'Should governments implement a carbon border tax on imports?', 'promptDescription': 'Should governments implement a carbon border tax on imports?', 'status': 'active', 'curr': False, 'sourceId': 'ENV-020', 'framesWeek': 'W6', 'framesFrame': 'Synthesis & Judgment', 'suggestedFocusArea': 'combined', 'suggestedPrimaryFrame': 'FRAME_06'},
]
for doc in docs:
    db.collection('passages').document(doc['passageId']).set(doc)
    print(f"Uploaded {doc['passageId']} — {doc['framesWeek']} {doc['framesFrame']}")
print(f'Done. {len(docs)} passages uploaded.')